### ISSUE TITLE
UDP Support

### ISSUE THREAD

**Issue by kelvinji2009** [DataSecs/Hydra#2]
First of all, `Hydar` is easy to use. Thanks.

As you know, custom udp protocol is very popular.

**Comment by DataSecs** [comment]
Hey kelvinji2009,

I'm happy to hear, that you think so about Hydra.
I do really like your idea and was thinking about it too. I'm going to add UDP support as soon as I'm going to have some free time to do it. That might be in something like 2 months.

I'll get back to you when UDP support is added and reference the issue.

**Comment by kelvinji2009** [comment]
@DataSecs Great. Thanks very much.

**Comment by DataSecs** [comment]
I am going to close this issue, as UDP has been added. Thank you again for bringing it up! :smile:
