### ISSUE TITLE
Any updates ?

### ISSUE THREAD

**Issue by aroooo** [DataSecs/Hydra#5]
Just discovered Hydra, thank you for creating this, Netty scared me and I didn't wanted to use it as is.
Last update was made 2 months ago, and i'm pretty sad if this project has been abandonned.
Are you planning to continue on maintaining this project ?
Thank you.

**Comment by DataSecs** [comment]
Hello @aroooo, I'm quite happy that Hydra is being helpful for you. It's nice to hear that the actual intent for the project seems to have worked! Unfortunately the project has been quite abandoned the past months. But your question actually did motivate me to again start working with the project.
I fixed some of the examples and enhanced them. There still is issue #2 that needs to be implemented, as UDP support is something quite crucial actually. I'm going to try to work on that matter and keep this project alive ^.^

**Comment by aroooo** [comment]
Thank you for your reply! Looking forward to see the improvements 😄
